modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = '''
Stone torches and torch arrows. A stone torch is crafted with stone sticks
and works just like a regular torch. Torch arrows place a torch wherever they land.
'''

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.1.219,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "the_fletching_table"
    type = "optional"
    ordering = "NONE"
    side = "BOTH"
